spring:
  profiles:
    active: dev

---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept


#eureka的配置，服务注册到哪里
eureka:
  client:
    service-url: #监控页面
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
      
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: springcloud-provider-dept


#eureka的配置，服务注册到哪里
eureka:
  client:
    service-url: #监控页面
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
      